import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import crypto from 'node:crypto';
const content=JSON.parse(fs.readFileSync(new URL('../private/content.json',import.meta.url)));const videos=JSON.parse(fs.readFileSync(new URL('../private/videos.json',import.meta.url)));const els=new Map();const el=s=>{if(!els.has(s))els.set(s,{innerHTML:'',textContent:'',style:{},value:'',classList:{toggle(){}},addEventListener(){},close(){},showModal(){}});return els.get(s)};let stored;let interval;
const context=vm.createContext({console,crypto,Blob,URL,Date,setTimeout:()=>1,clearTimeout(){},setInterval:f=>interval=f,document:{querySelector:el,querySelectorAll:()=>[],addEventListener(){},title:''},localStorage:{getItem:()=>null,setItem:(k,v)=>stored=v},window:{addEventListener(){},scrollTo(){}},location:{hash:'#dashboard'},fetch:async url=>({ok:true,status:200,json:async()=>url==='/content.json'?content:videos})});
const src=fs.readFileSync(new URL('../private/app.js',import.meta.url),'utf8');const exposed='\nreturn {render,prepare,start,submit,resultPage,validateImport,importFile,getState:()=>state,getContent:()=>content};';const api=await vm.runInContext('(async()=>{'+src+exposed+'})()',context);
assert.ok(el('#main').innerHTML.includes('Welcome'));for(const route of ['#learn','#videos','#exams','#revision','#team','#progress','#guide',...content.lessons.map(l=>'#lesson/'+l.id)]){context.location.hash=route;api.render();assert.ok(el('#main').innerHTML.length>200,route);assert.ok(!el('#main').innerHTML.includes('undefined'),route)}
api.prepare('mock:0');api.start();let state=api.getState();assert.equal(state.active.ids.length,50);assert.ok(state.active.deadline>Date.now());for(const id of state.active.ids)state.active.answers[id]=content.questions.find(q=>q.id===id).answer;state.active.index=49;api.render();assert.ok(el('#main').innerHTML.includes('QUESTION 50 OF 50'));api.submit();assert.equal(state.history.at(-1).score,100);assert.equal(state.history.at(-1).passed,true);assert.equal(state.active,null);assert.ok(stored.includes('Mock paper 1'));
api.prepare('mock:1');api.start();state.active.ids.slice(0,37).forEach(id=>state.active.answers[id]=content.questions.find(q=>q.id===id).answer);api.submit();assert.equal(state.history.at(-1).score,74);assert.equal(state.history.at(-1).passed,false);assert.equal(state.history.at(-1).items.filter(i=>i.answer===null).length,13);
api.prepare('simulation');api.start();assert.equal(state.active.ids.length,60);state.active.deadline=Date.now()-1;interval();assert.equal(state.active,null);assert.equal(state.history.at(-1).automatic,true);assert.equal(state.history.at(-1).score,0);
api.prepare('domain:orchestration');api.start();assert.equal(state.active.ids.length,10);assert.ok(state.active.ids.every(id=>content.questions.find(q=>q.id===id).domain==='orchestration'));assert.equal(state.active.deadline,null);api.submit();
const report=JSON.parse(stored);const imported=api.validateImport(report);assert.equal(imported.history.length,4);assert.throws(()=>api.validateImport({version:2}));report.history[0].score=2;assert.equal(api.validateImport(report).history[0].score,100);report.history[0].items[0].answer=9;assert.throws(()=>api.validateImport(report));
console.log('PASS: 28 page renders; 50-question scoring; 74% boundary; unanswered marking; 60-question timeout; targeted practice; saved history; import validation and recalculation.');
