import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import crypto from 'node:crypto';
const content=JSON.parse(fs.readFileSync(new URL('../private/content.json',import.meta.url)));const videos=JSON.parse(fs.readFileSync(new URL('../private/videos.json',import.meta.url)));const els=new Map();const el=s=>{if(!els.has(s))els.set(s,{innerHTML:'',textContent:'',style:{},value:'',classList:{toggle(){}},addEventListener(){},close(){},showModal(){}});return els.get(s)};let stored;let interval;const events=new Map();
const context=vm.createContext({console,crypto,Blob,URL,Date,setTimeout:()=>1,clearTimeout(){},setInterval:f=>interval=f,document:{querySelector:el,querySelectorAll:()=>[],addEventListener:(type,handler)=>events.set(type,handler),title:''},localStorage:{getItem:()=>null,setItem:(k,v)=>stored=v},window:{addEventListener(){},scrollTo(){}},location:{hash:'#dashboard'},fetch:async url=>({ok:true,status:200,json:async()=>url==='/content.json'?content:videos})});
const src=fs.readFileSync(new URL('../private/app.js',import.meta.url),'utf8');const exposed=`\nreturn {render,prepare,start,submit,resultPage,validateImport,importFile,getState:()=>state,getContent:()=>content,loadStudyLibrary,librarySafeLink,libraryResults,setLibrary:v=>{studyLibrary=v;libraryStatus='ready'},setLibraryFilters:(query='',category='all',type='all')=>{libraryQuery=query;libraryCategory=category;libraryType=type}};`;const api=await vm.runInContext('(async()=>{'+src+exposed+'})()',context);
assert.ok(el('#main').innerHTML.includes('Welcome'));for(const route of ['#learn','#videos','#exams','#revision','#team','#progress','#guide',...content.lessons.map(l=>'#lesson/'+l.id)]){context.location.hash=route;api.render();assert.ok(el('#main').innerHTML.length>200,route);assert.ok(!el('#main').innerHTML.includes('undefined'),route)}
api.prepare('mock:0');api.start();let state=api.getState();assert.equal(state.active.ids.length,50);assert.ok(state.active.deadline>Date.now());for(const id of state.active.ids)state.active.answers[id]=content.questions.find(q=>q.id===id).answer;state.active.index=49;api.render();assert.ok(el('#main').innerHTML.includes('QUESTION 50 OF 50'));api.submit();assert.equal(state.history.at(-1).score,100);assert.equal(state.history.at(-1).passed,true);assert.equal(state.active,null);assert.ok(stored.includes('Mock paper 1'));
api.prepare('mock:1');api.start();state.active.ids.slice(0,37).forEach(id=>state.active.answers[id]=content.questions.find(q=>q.id===id).answer);api.submit();assert.equal(state.history.at(-1).score,74);assert.equal(state.history.at(-1).passed,false);assert.equal(state.history.at(-1).items.filter(i=>i.answer===null).length,13);
api.prepare('simulation');api.start();assert.equal(state.active.ids.length,60);state.active.deadline=Date.now()-1;interval();assert.equal(state.active,null);assert.equal(state.history.at(-1).automatic,true);assert.equal(state.history.at(-1).score,0);
api.prepare('domain:orchestration');api.start();assert.equal(state.active.ids.length,10);assert.ok(state.active.ids.every(id=>content.questions.find(q=>q.id===id).domain==='orchestration'));assert.equal(state.active.deadline,null);api.submit();
const report=JSON.parse(stored);const imported=api.validateImport(report);assert.equal(imported.history.length,4);assert.throws(()=>api.validateImport({version:2}));report.history[0].score=2;assert.equal(api.validateImport(report).history[0].score,100);report.history[0].items[0].answer=9;assert.throws(()=>api.validateImport(report));
console.log('PASS: 28 page renders; 50-question scoring; 74% boundary; unanswered marking; 60-question timeout; targeted practice; saved history; import validation and recalculation.');

const studyFixture={configured:true,updatedAt:'2026-10-08',summary:'Revision explanations',notes:[{id:'sample-note',title:'Example <script>note</script>',category:'Basics',body:'Explain a useful distinction.\n\nSecond paragraph.',bullets:['Remember the idea.'],tags:['example'],sources:[{label:'Test reference',url:'https://example.com/reference'}]}],resources:[],questions:[{id:'sample-check',noteId:'sample-note',prompt:'Select a useful distinction',options:['Correct choice','Distractor'],answer:0,explanation:'This explains the choice.'}]};
api.setLibrary(studyFixture);context.location.hash='#library';api.render();let libraryHtml=el('#main').innerHTML;assert.ok(libraryHtml.includes('Explain a useful distinction.'));assert.ok(libraryHtml.includes('&lt;script&gt;note&lt;/script&gt;'));assert.ok(!libraryHtml.includes('<script>note</script>'));assert.ok(libraryHtml.includes('Source details'));assert.ok(libraryHtml.includes('Knowledge checks'));assert.ok(!libraryHtml.includes('href="https://example.com/reference"'));assert.ok(!libraryHtml.includes('This explains the choice.'));assert.ok(!libraryHtml.includes('Supporting material'));assert.equal(api.librarySafeLink('javascript:alert(1)'),'');assert.equal(api.librarySafeLink('https://u:p@example.com'),'');
api.setLibraryFilters('','all','questions');assert.ok(api.libraryResults().includes('sample-check'));assert.ok(!api.libraryResults().includes('id="study-note-sample-note"'));api.setLibraryFilters('','all','notes');assert.ok(api.libraryResults().includes('id="study-note-sample-note"'));assert.ok(!api.libraryResults().includes('sample-check'));api.setLibraryFilters('remember');assert.ok(api.libraryResults().includes('sample-note'));api.setLibraryFilters('absent');assert.ok(api.libraryResults().includes('No matching notes'));api.setLibraryFilters('','Basics');assert.ok(api.libraryResults().includes('sample-check'));api.setLibraryFilters('','Other');assert.ok(api.libraryResults().includes('No matching notes'));api.setLibraryFilters();
events.get('click')({target:{closest:()=>({dataset:{libraryAnswer:'sample-check:1'},hasAttribute:()=>false})}});assert.ok(el('#library-results').innerHTML.includes('Review this distinction.'));assert.ok(el('#library-results').innerHTML.includes('This explains the choice.'));assert.equal(api.getState().history.length,4);
events.get('click')({target:{closest:()=>({dataset:{libraryAnswer:'sample-check:0'},hasAttribute:()=>false})}});assert.ok(el('#library-results').innerHTML.includes('Correct.'));
api.setLibrary({...studyFixture,notes:[],questions:[]});api.render();assert.ok(el('#main').innerHTML.includes('Study notes are being prepared'));
context.fetch=async()=>({ok:false,status:503});await api.loadStudyLibrary();assert.ok(el('#main').innerHTML.includes('The study notes could not load'));
context.fetch=async()=>({ok:true,status:200,json:async()=>studyFixture});await api.loadStudyLibrary();assert.ok(el('#main').innerHTML.includes('Explain a useful distinction.'));
context.fetch=async()=>({ok:false,status:401});await api.loadStudyLibrary();assert.equal(context.location.href,'/');
console.log('PASS: study note rendering and escaping; search and topic filters; supplementary answers; unchanged mock history; empty/error/retry and expired-session handling.');
