export const domains=[{id:'fundamentals',name:'Kubernetes Fundamentals',short:'Fundamentals',weight:44,color:'#7357ff'},{id:'orchestration',name:'Container Orchestration',short:'Orchestration',weight:28,color:'#168fbd'},{id:'delivery',name:'Cloud Native Application Delivery',short:'App delivery',weight:16,color:'#de7a36'},{id:'architecture',name:'Cloud Native Architecture',short:'Architecture',weight:12,color:'#24977a'}];
export const lessons=[];
const add=(id,domain,title,minutes,focus,body,remember,trap,exercise,source)=>lessons.push({id,domain,title,minutes,focus,body,remember,trap,exercise,source});
add('containers','fundamentals','Containers, images & runtimes',20,'Containerization',[
'A container packages an application with its user-space dependencies. Linux containers share the host kernel, while a virtual machine runs its own guest operating system. This makes containers efficient, but does not make a container equivalent to a complete VM or a perfect security boundary.',
'An image is an immutable, layered template. A running container adds writable state. A registry stores images; a runtime starts and manages containers. OCI defines image and runtime specifications. Kubernetes communicates with compatible runtimes such as containerd and CRI-O through the Container Runtime Interface (CRI).',
'For a Nutanix infrastructure team, think of worker nodes as machines that could run on AHV. Kubernetes schedules Pods onto those nodes; it does not replace the hypervisor. Image tags can move, while a digest identifies specific image content.'
],['Image → template; container → running instance','CRI connects Kubernetes to runtimes; OCI defines standards','Namespaces isolate views; cgroups control resource usage'],'Docker-built images can run on Kubernetes without Docker Engine being the node runtime.','Explain image, registry and runtime to a colleague without using the word Docker.','https://kubernetes.io/docs/concepts/containers/');
add('control-plane','fundamentals','The control plane & worker nodes',25,'Kubernetes Core Concepts',[
'A Kubernetes cluster has a control plane and worker nodes. The API server exposes the Kubernetes API. Clients and components use that API to read or change cluster objects. etcd is the backing store for cluster state, not a database for your business application.',
'The scheduler selects a suitable node for an unscheduled Pod. Controllers repeatedly compare desired state with observed state and act to reduce differences. For example, if a Deployment needs three replicas and one disappears, its controllers create a replacement.',
'On each worker, the kubelet ensures that assigned Pods run through the container runtime. The networking implementation provides Service traffic routing, commonly using kube-proxy or an alternative implementation. The scheduler chooses a node; the kubelet manages execution there.'
],['API server: API entry point','etcd: cluster state','Scheduler: placement; kubelet: node execution'],'The scheduler does not start containers itself.','Draw the path: kubectl → API server → scheduling → kubelet → runtime. Say where desired state is stored.','https://kubernetes.io/docs/concepts/overview/components/');
add('objects','fundamentals','Objects, YAML & reconciliation',20,'Kubernetes Core Concepts',[
'An API object describes something in the cluster. Common manifest fields include apiVersion, kind, metadata and spec. The spec expresses desired state. Status describes what the system has observed and is normally maintained by Kubernetes.',
'Declarative management means submitting the desired outcome and allowing controllers to reconcile it. Imperative commands describe individual actions. kubectl apply can manage a declarative manifest; repeatedly applying a consistent desired state should converge on that state.',
'Labels are key-value identifiers used to select related objects. Annotations hold non-identifying metadata. A Service selector can match labels on Pods. A label mismatch is a common reason for a Service to have no usable endpoints.'
],['spec = desired; status = observed','Labels support selection; annotations hold metadata','Reconciliation is ongoing, not a one-time script'],'YAML indentation matters, but KCNA preparation should focus on what the object means.','Read a Deployment manifest and point out its name, desired replicas, image and Pod labels.','https://kubernetes.io/docs/concepts/overview/working-with-objects/');
add('pods','fundamentals','Pods & container lifecycle',20,'Kubernetes Core Concepts',[
'A Pod is the smallest deployable Kubernetes unit. One or more closely coupled containers share its network namespace and can share volumes. Containers in the same Pod can communicate using localhost; separate Pods have separate network identities.',
'Pods are disposable. A replacement Pod is a new object and may have a new IP address. A controller manages replacement, and a Service provides a stable access point. A bare Pod is not automatically recreated as a new Pod after its node is lost.',
'Init containers normally complete in order before application containers start. A sidecar supports the main application, for example by forwarding logs or proxying traffic. Do not put unrelated services together just because they can share a Pod.'
],['Pod containers share an IP and port space','Pod IPs are not durable service addresses','Use controllers for replacement and scaling'],'A container restart inside a Pod is different from replacing the whole Pod.','Explain why two independent web applications usually belong in separate Pods.','https://kubernetes.io/docs/concepts/workloads/pods/');
add('controllers','fundamentals','Choose the right workload controller',25,'Kubernetes Core Concepts',[
'A Deployment manages replicated applications and supports controlled rollouts, usually through ReplicaSets. It is a common choice for stateless services. A ReplicaSet maintains a requested number of matching Pods.',
'A StatefulSet gives Pods stable identities and supports stable storage association and ordered behavior. Use it when identity and persistent state matter. It does not automatically make a database highly available or back up its data.',
'A DaemonSet places a Pod on each eligible node, useful for node agents. A Job runs work to completion. A CronJob creates Jobs on a schedule. Choose based on the required behavior: replicas, identity, per-node presence, completion or scheduling.'
],['Deployment: replicated app; StatefulSet: stable identity','DaemonSet: eligible nodes','Job: finish work; CronJob: scheduled work'],'A CronJob schedules Jobs, not worker nodes.','Map these needs: web frontend, log agent, nightly report, database replicas and one-off migration.','https://kubernetes.io/docs/concepts/workloads/');
add('namespaces','fundamentals','Namespaces, contexts & kubectl',20,'Administration',[
'Namespaces group namespaced API resources. Teams can use them to organize workloads, apply quotas and scope access. Namespaces do not by themselves provide complete network isolation. Nodes and PersistentVolumes are examples of cluster-scoped resources.',
'A kubeconfig stores cluster connection details, users and contexts. A context selects a cluster, identity and optional default namespace. Check it before issuing commands, particularly if your team manages multiple environments.',
'Know the intent of kubectl get, describe, logs, exec, apply and delete. get lists resources, describe reveals details and events, logs reads container output, and exec runs a command inside a container. Read-only inspection should come before making changes.'
],['Context selects cluster + identity + namespace','get → overview; describe → details/events','Namespaces organize resources, not virtual machines'],'Changing the namespace does not switch clusters.','In a disposable learning cluster, run kubectl config current-context and kubectl get pods -A. Explain each output.','https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/');
add('scheduling','fundamentals','Scheduling & resource management',25,'Scheduling',[
'The scheduler filters and scores nodes for unscheduled Pods. It considers resource requests and placement rules. CPU and memory requests guide placement; limits constrain usage. A node can appear idle but still lack enough unallocated requested resources for a Pod.',
'nodeSelector matches node labels. Node affinity provides more expressive placement rules. Taints repel Pods unless they have suitable tolerations. A toleration allows a Pod to be considered for a node; it does not guarantee that the Pod will land there.',
'CPU limits can cause throttling. Exceeding a memory limit can lead to termination for out-of-memory usage. ResourceQuota constrains aggregate consumption in a namespace, while LimitRange can provide per-object defaults and bounds.'
],['Requests influence scheduling; limits constrain usage','Toleration permits placement; affinity influences selection','Pending often points to placement or storage constraints'],'A toleration is not an instruction to schedule on one specific node.','A Pod requests 8 GiB but each node has only 4 GiB available for requests. Explain why adding a CPU limit will not fix scheduling.','https://kubernetes.io/docs/concepts/scheduling-eviction/');
add('configuration','fundamentals','Configuration, Secrets & scaling',20,'Administration',[
'A ConfigMap separates non-confidential configuration from an image. A Secret stores sensitive values for use by workloads. Base64 encoding is not encryption. Secret safety also depends on access controls, encryption configuration and careful handling.',
'Configuration can be exposed as environment variables or mounted files. Updating a ConfigMap does not automatically update environment variables inside an already running process. Some mounted file updates propagate, but the application must still reload them as needed.',
'The Horizontal Pod Autoscaler changes replica counts using observed metrics. A node autoscaler changes available node capacity. These address different problems: more application instances versus more places to run them. Reliable metrics and meaningful resource requests are important for utilization-based scaling.'
],['ConfigMap: non-sensitive configuration; Secret: sensitive data','HPA: replicas; node autoscaler: nodes','Base64 is reversible encoding'],'Scaling Pods is not the same as increasing each Pod’s CPU or memory.','Choose where to store a log level and a database password. Explain what happens to existing environment variables after a change.','https://kubernetes.io/docs/concepts/configuration/');
add('services','orchestration','Services, DNS & traffic paths',25,'Networking',[
'A Service gives a stable network abstraction for reaching a changing set of Pods. ClusterIP is the usual internal-only Service type. NodePort exposes a port on nodes, while LoadBalancer integrates with an implementation that provides an external load balancer.',
'Cluster DNS lets workloads discover Services by name. A Service usually selects Pods using labels; EndpointSlices track the relevant endpoints. If connectivity fails, check selectors, Pod readiness, ports and DNS before assuming the network is broken.',
'An Ingress describes HTTP/HTTPS routing rules and needs an Ingress controller to implement them. A Service is not itself a layer-7 URL router. NetworkPolicy defines permitted traffic where supported by the networking plugin; creating a namespace alone does not enforce it.'
],['Service: stable access to changing Pods','Ingress requires a controller','DNS names are preferable to hard-coded Pod IPs'],'Declaring a LoadBalancer Service does not guarantee an external IP on every cluster.','Trace browser → load balancer/Ingress controller → Service → ready Pod.','https://kubernetes.io/docs/concepts/services-networking/');
add('interfaces','orchestration','CNI, CSI, CRI & service meshes',20,'Networking',[
'Kubernetes relies on extension interfaces. CRI connects kubelet to container runtimes. CNI is used by networking plugins for container networking. CSI allows storage providers to integrate volume operations. Match the acronym to the concern before learning individual products.',
'A service mesh adds capabilities to service-to-service communication such as traffic policies, telemetry and workload identity. Some designs use sidecars; others use different data-plane architectures. Kubernetes does not require a mesh for basic networking.',
'Keep responsibility boundaries clear. A container runtime launches containers. A network plugin connects Pods. A storage driver handles volume operations. A mesh controls application traffic behavior above the basic network.'
],['CRI = runtime; CNI = networking; CSI = storage','A service mesh is optional','Mesh telemetry complements application instrumentation'],'CSI does not schedule Pods and CNI does not pull images.','For an AHV-hosted cluster with a volume mount problem, identify the Kubernetes interface you would investigate first.','https://kubernetes.io/docs/concepts/extend-kubernetes/');
add('rbac','orchestration','Authentication, RBAC & least privilege',25,'Security',[
'Authentication answers who is making the request. Authorization decides what that identity may do. Admission control then validates or mutates applicable requests before persistence. A successful login does not imply permission to list every resource.',
'RBAC rules specify API groups, resources and verbs. Roles are namespaced. ClusterRoles can express cluster-scoped rules or reusable namespaced rules. A RoleBinding grants permissions within its namespace, including when it refers to a ClusterRole; a ClusterRoleBinding grants them across the cluster.',
'ServiceAccounts provide workload identities. Prefer narrow permissions and dedicated identities. Do not give a backup process cluster-admin merely because it needs to read selected resources. In a Nutanix context, this is similar in intent to separating operational roles, but Kubernetes RBAC is a separate authorization system.'
],['Authentication = identity; authorization = permissions','RoleBinding scope is its namespace','ServiceAccount = workload identity'],'Referencing a ClusterRole from a RoleBinding does not automatically grant cluster-wide access.','Define the smallest permissions needed by a tool that only lists Pods in a single namespace.','https://kubernetes.io/docs/reference/access-authn-authz/rbac/');
add('hardening','orchestration','Workload & supply-chain security',20,'Security',[
'Use trusted images, scan for known vulnerabilities and keep dependencies current. Prefer immutable references for reproducibility. Image signing and provenance help establish where software came from; they do not prove that it has no vulnerabilities.',
'Run workloads with the privileges they need. Common controls include non-root execution, dropping Linux capabilities, a read-only root filesystem and preventing privilege escalation. Pod Security admission can enforce Pod Security Standards at namespace level.',
'NetworkPolicy can restrict ingress and egress for selected Pods when enforced by the networking implementation. TLS protects traffic in transit. Neither a namespace nor a base64-encoded Secret substitutes for these controls.'
],['Least privilege applies to API access and container execution','Verify provenance and scan dependencies','NetworkPolicy requires an enforcing implementation'],'An image with no known CVEs today is not guaranteed safe forever.','Review a sample manifest for privileged mode, root user, unnecessary mounts and broad permissions.','https://kubernetes.io/docs/concepts/security/');
add('storage','orchestration','Volumes, PVs, PVCs & StorageClasses',25,'Storage',[
'Container writable filesystems are ephemeral. Volumes provide storage to containers in a Pod. emptyDir lasts with the Pod and can survive an individual container restart, but is lost when the Pod is removed.',
'A PersistentVolume (PV) represents storage in the cluster. A PersistentVolumeClaim (PVC) requests storage for a workload. A StorageClass describes a class of storage and commonly enables dynamic provisioning through a driver. The Pod consumes the PVC; the claim binds to a suitable volume.',
'For an infrastructure team, separate the backing storage platform from its Kubernetes objects. CSI bridges to storage capabilities; a PVC is the application’s request. ReadWriteOnce generally permits read-write mounting by a single node, not necessarily a single Pod. Reclaim policy affects what happens to storage after a claim is released.'
],['PVC requests; PV provides; StorageClass describes provisioning','emptyDir is tied to Pod lifetime','Persistence does not replace backup'],'ReadWriteOnce does not mean one Pod in all circumstances.','Explain why a database needs persistent storage even if Kubernetes can recreate its Pod.','https://kubernetes.io/docs/concepts/storage/');
add('triage','orchestration','Troubleshoot by symptoms',25,'Troubleshooting',[
'Work from evidence. For Pending, inspect events for resource constraints, placement rules or unbound storage. For ImagePullBackOff, inspect image names, tags, registry access and pull credentials. For CrashLoopBackOff, inspect the application’s logs, exit reason, configuration and probes.',
'Use kubectl describe pod for events and container state. kubectl logs --previous can reveal output from the previous terminated container instance. If a Service has no traffic, inspect its selectors, EndpointSlices, target port and readiness state.',
'Separate infrastructure symptoms from application symptoms. An HTTP 500 can indicate an application problem even when the network path works. A DNS lookup failure has different evidence from a process that cannot open its configuration file. Avoid deleting resources before collecting useful evidence.'
],['Pending: placement/storage; ImagePullBackOff: image retrieval','CrashLoopBackOff: repeated exits','Collect events and logs before changing state'],'BackOff describes retry behavior; it is not the underlying root cause.','Choose the first two checks for a Pending Pod and for a repeatedly crashing Pod.','https://kubernetes.io/docs/tasks/debug/debug-application/');
add('delivery-pipeline','delivery','CI/CD & immutable delivery',25,'Application Delivery',[
'Continuous integration builds and tests frequent code changes. Continuous delivery keeps a change ready for release, often with a manual production approval. Continuous deployment automatically releases changes that pass the required checks.',
'A typical pipeline tests code, builds an image, scans it, publishes it and updates deployment configuration. Build once and promote the same immutable artifact through environments. Rebuilding separately for production can introduce differences from what was tested.',
'Kubernetes handles workload orchestration; it is not a complete source-code build system. Tooling such as CI runners, registries and delivery controllers supplies the other stages. Health checks and observability help determine whether a release is actually working.'
],['CI builds/tests; CD delivers or deploys','Promote a tested artifact','A successful build does not prove a healthy release'],'Continuous delivery and continuous deployment differ at the production release decision.','Sketch your team’s path from a code commit to a healthy running application.','https://glossary.cncf.io/continuous-delivery/');
add('gitops','delivery','GitOps, drift & reconciliation',25,'Application Delivery',[
'GitOps stores desired system state declaratively in version control. An agent pulls that state and reconciles the running environment toward it. Reviewable commits provide change history and a place to apply team approval practices.',
'Argo CD and Flux are examples of GitOps tooling. A running cluster can drift when someone makes an out-of-band change. A configured controller can detect the difference and, depending on policy, reconcile it. GitOps is more than putting a script in a Git repository.',
'Reverting a configuration commit can restore earlier desired state, but that does not automatically reverse database migrations or data changes. Secrets require a deliberate secure workflow; a private repository alone is not sufficient protection for plaintext credentials.'
],['Declarative + versioned + pulled + continuously reconciled','GitOps detects differences between desired and live state','Database rollback needs separate thought'],'GitOps does not mean every git push must deploy immediately without review.','A manual replica change keeps reverting. Explain what a GitOps controller might be doing.','https://opengitops.dev/');
add('releases','delivery','Rollouts, Helm & release strategies',25,'Application Delivery',[
'A rolling update gradually replaces old replicas with new ones. maxSurge permits temporary extra Pods, while maxUnavailable limits unavailable replicas. Readiness determines whether a Pod should receive Service traffic.',
'Blue-green delivery keeps old and new environments and switches traffic. Canary delivery exposes a limited audience or traffic fraction to a new version before wider rollout. These strategies require appropriate traffic control and useful health signals; a Deployment alone does not provide every advanced traffic-splitting behavior.',
'Helm packages related Kubernetes manifests into charts with configurable values. A release is an installed chart instance. Kustomize applies overlays to base manifests. Both help manage configuration, but neither eliminates the need to understand the underlying Kubernetes resources.'
],['Rolling: gradual replacement; canary: limited exposure','Blue-green: switch between environments','Helm chart = package; release = installation'],'A rollout can complete while the application still has a functional bug.','Pick a strategy for testing a risky feature with 5% of traffic, and explain the signal you would monitor.','https://kubernetes.io/docs/concepts/workloads/controllers/deployment/');
add('probes','delivery','Probes & application debugging',25,'Debugging',[
'A readiness probe determines whether a container is ready to serve traffic. Failing readiness normally removes the Pod from matching Service endpoints without restarting the container. A liveness probe detects when restarting a container may help. A startup probe protects slow startup by delaying liveness and readiness probing until startup succeeds.',
'Probe design matters. A liveness check that fails whenever an external dependency is unavailable can trigger unnecessary restart loops. Readiness can be used to stop new traffic while the application is temporarily unable to serve it.',
'For a failed release, inspect rollout status, events, image changes, configuration and logs. Compare the new version with the last healthy one. kubectl rollout undo can restore a Deployment revision, but persistent data and external dependencies may still need separate recovery.'
],['Readiness: receive traffic','Liveness: restart a stuck container','Startup: allow initial boot time'],'Readiness failure does not itself restart a container.','A Java service takes two minutes to start and is killed repeatedly after 30 seconds. Which probe design needs attention?','https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/');
add('observability','architecture','Metrics, logs, traces & OpenTelemetry',25,'Observability',[
'Metrics are numerical measurements over time, useful for rates, counts and distributions. Logs record events. Distributed traces connect spans across a request’s path through services. Use them together: an error-rate metric shows a trend, a trace identifies the slow service, and logs add local context.',
'Prometheus collects and queries time-series metrics, commonly by scraping endpoints. Grafana visualizes data from multiple sources. OpenTelemetry supplies vendor-neutral instrumentation and telemetry collection/export building blocks; it is not itself a complete storage and dashboard backend.',
'A service-level indicator (SLI) measures user-facing behavior. A service-level objective (SLO) sets a target for that indicator. An error budget expresses tolerated unreliability over a period. Alert on actionable symptoms rather than every harmless transient fluctuation.'
],['Metrics: how much; logs: events; traces: request path','Prometheus collects metrics; Grafana visualizes','SLI measures; SLO targets'],'A trace is not simply a long log file, and OpenTelemetry is not a dashboard product.','For high checkout latency, choose a metric, a trace and a log entry that would each help.','https://opentelemetry.io/docs/concepts/observability-primer/');
add('cloud-native','architecture','Cloud native principles & trade-offs',25,'Cloud Native Ecosystem and Principles',[
'Cloud native systems use patterns such as declarative automation, loosely coupled services and resilient infrastructure to make changes more safely and frequently. Running on a public cloud is not a requirement: cloud native workloads can run on premises, including on infrastructure managed by your team.',
'Microservices can enable independent deployment and scaling, but introduce network calls, distributed failure modes and operational overhead. A well-designed modular monolith may be the better choice for some teams. Containers alone do not make an architecture resilient.',
'Design for failure: use redundancy, timeouts, bounded retries and graceful degradation where appropriate. Horizontal scaling adds instances; vertical scaling increases resources per instance. Serverless abstracts more infrastructure operations but does not remove the servers underneath.'
],['Cloud native is an operating approach, not a hosting location','Resilience must be designed and observed','Microservices create trade-offs, not automatic benefits'],'Moving an unchanged VM to public cloud is not by itself a cloud native transformation.','Describe one benefit and one operational cost of splitting a monolith into services.','https://glossary.cncf.io/cloud-native/');
add('ecosystem','architecture','CNCF projects & open-source collaboration',20,'Cloud Native Community and Collaboration',[
'The Cloud Native Computing Foundation supports a vendor-neutral ecosystem of projects and communities. Learn what categories of tools do before memorizing logos: orchestration, runtimes, networking, storage, observability and delivery.',
'Project maturity levels include Sandbox, Incubating and Graduated. They reflect project and community maturity criteria; they are not a promise that a project is the best fit for every workload. Consult the live CNCF landscape when making actual product choices because status can change.',
'Open-source collaboration includes issue reports, documentation, reviews, testing and code. Follow each project’s contribution guide and code of conduct. Kubernetes SIGs focus on particular subject areas. A useful issue includes a reproducible problem, environment details and relevant sanitized evidence.'
],['Know tool purpose before project trivia','Sandbox → Incubating → Graduated','Documentation and testing are valid contributions'],'CNCF membership does not mean every member product is a CNCF-hosted project.','Find a project contribution guide and describe a useful non-code contribution your team could make.','https://www.cncf.io/projects/');
